## Packages and modules
-------------------------------------
       Package :- Collection of modules
       Module :- Collection of functions 

       2 types of modules 
       ----------------
       1.builtin module :-  os,keyword,random,math,....etc
       2.user defined module :-  Collection of classes,functions ...etc

In [3]:
import math
print(math.sqrt(25))
print(math.ceil(5.9))
print(math.floor(5.9))

5.0
6
5


In [4]:
import keyword
print(keyword.kwlist)

['False', 'None', 'True', '__peg_parser__', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [9]:
from package import module

In [10]:
module.evenodd(4)

Even


In [11]:
module.evenodd(3)

odd


In [12]:
module.palindrom('level')

palindrom


In [13]:
module.palindrom('mom')

palindrom


In [14]:
module.palindrom('abcd')

not palindrom


In [15]:
print(dir(module))

['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'evenodd', 'n', 'palindrom']


In [ ]:
# Data Science 
   - numpy
   - pandas
   - matplot
   - seaborn 

In [ ]:
- Numpy
   * Numpy is a python library used for working with arrays
   * numpy (numerical python)
   * It is a fundamental package for scientific computing in python
   * It is a data science packge
   * It is an open source python library
    
how to install numpy library
------------------------
pip install numpy

In [16]:
import numpy 

In [21]:
import numpy as np

In [22]:
# 0 - dimensional array
a = np.array(3)
print(a)

3


In [24]:
# 1- dimensional array
a1 = np.array([1,2,3,4,5])
print(a1)
print(type(a1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [25]:
# 2-dimensional array
a2 = np.array([[1,2,3],[4,5,6]])
print(a2,type(a2))

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>


In [26]:
# 3-dimensional array
a3 = np.array([[56,67,11],[77,8,9],[44,7,72]])
print(a3,type(a3))

[[56 67 11]
 [77  8  9]
 [44  7 72]] <class 'numpy.ndarray'>


In [28]:
# combination of 2d
a3 = np.array([[[56,67,11],[77,8,9],[44,7,72]],
               [[56,67,11],[77,8,9],[44,7,72]]])
print(a3,type(a3))
print(a3.ndim)

[[[56 67 11]
  [77  8  9]
  [44  7 72]]

 [[56 67 11]
  [77  8  9]
  [44  7 72]]] <class 'numpy.ndarray'>
3


In [34]:
# builtin functions in numpy
print(a2)
print(a2.shape) # no of rows and columns
print(a2.size) # total no of elements 
print(a2.itemsize)
print(a2.ndim) # dimensional
print(a2.dtype) # which datatype

[[1 2 3]
 [4 5 6]]
(2, 3)
6
4
2
int32


In [35]:
a = np.array([1,2,3,4],dtype=float)
print(a)

[1. 2. 3. 4.]


In [36]:
a = np.array([1,2,3,4],dtype=complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [37]:
print(a2)

[[1 2 3]
 [4 5 6]]


In [40]:
print(a2.sum())
print(a2.min())
print(a2.max())

21
1
6


In [41]:
n = np.array([2,4,9.7,'a','c',44])
print(n)

['2' '4' '9.7' 'a' 'c' '44']


In [43]:
n1 = np.array((34,65,78,12,89))
print(n1,type(n1))

[34 65 78 12 89] <class 'numpy.ndarray'>


In [44]:
print(dir(numpy),end=' ')

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spe

In [46]:
# range()
n = np.array(range(10))
print(n)

[0 1 2 3 4 5 6 7 8 9]


In [48]:
n1 = np.array(range(100))
print(n1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [49]:
n2 = np.array(range(1,100,3))
print(n2)

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70
 73 76 79 82 85 88 91 94 97]


In [62]:
# arange()
import numpy as np
n4 = np.array(np.arange(10,20))
print(n4)

[10 11 12 13 14 15 16 17 18 19]


In [64]:
n5 = np.array(np.arange(1.5,10.5))
print(n5)

[1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]


In [65]:
n3 = np.arange(10.5,23.5,2)
n3

array([10.5, 12.5, 14.5, 16.5, 18.5, 20.5, 22.5])

In [72]:
# zero's method
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [70]:
a2 = np.zeros(5,dtype=int)
a2

array([0, 0, 0, 0, 0])

In [69]:
a1 = np.zeros((2,2),dtype=int)
a1

array([[0, 0],
       [0, 0]])

In [74]:
s = np.zeros((3,3),dtype=int)
s

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [75]:
# one's method
d = np.ones(3)
d

array([1., 1., 1.])

In [76]:
d1 = np.ones((3,3),dtype=int)
d1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [77]:
# identity matrix
d2 = np.eye(2)
d2

array([[1., 0.],
       [0., 1.]])

In [78]:
d3 = np.eye(5,dtype=int)
d3

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [80]:
np.diag([3,4,5,6])

array([[3, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 6]])

In [81]:
# full()
np.full(4,7)

array([7, 7, 7, 7])

In [82]:
np.full(10,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [83]:
np.full((2,2),8)

array([[8, 8],
       [8, 8]])

In [84]:
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [88]:
# Arithmetic operations
import numpy as np
a = np.array([[1,2],[3,4]])
print('a matrix is : ')
print(a)
b = np.array([[5,6],[8,9]])
print('b matrix is : ')
print(b)

a matrix is : 
[[1 2]
 [3 4]]
b matrix is : 
[[5 6]
 [8 9]]


In [90]:
print(a+b)
print(a-b)

[[ 6  8]
 [11 13]]
[[-4 -4]
 [-5 -5]]


In [91]:
# matrix multiplication using dot method
print(a.dot(b))

[[21 24]
 [47 54]]


In [100]:
# random()
import random
print(random.randint(10,20))

16


In [103]:
print(np.random.randint(10,50,5))

[30 12 33 49 39]


In [106]:
print(np.random.randint(10,50,(3,3)))

[[32 16 36]
 [14 19 17]
 [14 34 11]]


In [107]:
print(np.random.randn(4,3))

[[ 0.26397654  0.38748709  1.25288379]
 [-0.9640715  -0.77130223  0.70324286]
 [-1.74060754  0.85189646  0.39624361]
 [-0.829048   -0.57924759  1.69800859]]


In [109]:
n = np.random.randint(10,50,(4,4))
print(n)

[[26 27 33 23]
 [17 17 36 17]
 [34 17 19 33]
 [38 19 12 47]]


In [114]:
print(n[0],n[1],n[2][2],n[3][3])

[26 27 33 23] [17 17 36 17] 19 47


In [112]:
print(n[::-1]) # reverse matrix

[[38 19 12 47]
 [34 17 19 33]
 [17 17 36 17]
 [26 27 33 23]]


In [115]:
# Boolean indexing
print(n>20)

[[ True  True  True  True]
 [False False  True False]
 [ True False False  True]
 [ True False False  True]]


In [116]:
print(n<20)

[[False False False False]
 [ True  True False  True]
 [False  True  True False]
 [False  True  True False]]


In [117]:
print(n%2==0) # even

[[ True False False False]
 [False False  True False]
 [ True False False False]
 [ True False  True False]]


In [118]:
print(n%2!=0) # odd

[[False  True  True  True]
 [ True  True False  True]
 [False  True  True  True]
 [False  True False  True]]


In [119]:
# fancy indexing - it will returns values
print(n)

[[26 27 33 23]
 [17 17 36 17]
 [34 17 19 33]
 [38 19 12 47]]


In [120]:
print(n[n%2==0]) # print even values

[26 36 34 38 12]


In [121]:
print(n[n%2!=0]) # print odd values

[27 33 23 17 17 17 17 19 33 19 47]


In [ ]:
# reshape()
  - based on the elements we can reshape the matrix
  - converting 1-d to 2-d , 2-d to 3-d ....etc

In [126]:
import numpy as np
n = np.arange(20).reshape(4,5)
n

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [127]:
n1 = np.arange(15).reshape(5,3)
n1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [134]:
m = np.random.randint(1,30,(10,3))
m

array([[ 6,  2,  5],
       [28, 19, 26],
       [13, 19, 15],
       [19, 16, 27],
       [13, 18,  9],
       [ 5,  2,  7],
       [ 7, 27, 24],
       [19, 20, 27],
       [15,  6, 18],
       [14, 26, 10]])

In [142]:
# slicing 
print(m[0],m[3:9])
print(m[0:4],m[2:6])
print(m[5:],m[3:7])
print(m[:4])

[6 2 5] [[19 16 27]
 [13 18  9]
 [ 5  2  7]
 [ 7 27 24]
 [19 20 27]
 [15  6 18]]
[[ 6  2  5]
 [28 19 26]
 [13 19 15]
 [19 16 27]] [[13 19 15]
 [19 16 27]
 [13 18  9]
 [ 5  2  7]]
[[ 5  2  7]
 [ 7 27 24]
 [19 20 27]
 [15  6 18]
 [14 26 10]] [[19 16 27]
 [13 18  9]
 [ 5  2  7]
 [ 7 27 24]]
[[ 6  2  5]
 [28 19 26]
 [13 19 15]
 [19 16 27]]


In [145]:
print(m[0:6:2])
print(m[::-1])

[[ 6  2  5]
 [13 19 15]
 [13 18  9]]
[[14 26 10]
 [15  6 18]
 [19 20 27]
 [ 7 27 24]
 [ 5  2  7]
 [13 18  9]
 [19 16 27]
 [13 19 15]
 [28 19 26]
 [ 6  2  5]]


In [146]:
np.exp(3)

20.085536923187668

In [147]:
np.exp(1)

2.718281828459045

In [153]:
np.sin(0)

0.0

In [154]:
np.tan(0)

0.0

In [155]:
np.cos(1)

0.5403023058681398

In [156]:
np.log(3)

1.0986122886681098

In [157]:
np.log([2,3,4,5])

array([0.69314718, 1.09861229, 1.38629436, 1.60943791])